### ISSUE TITLE
SECURITY.md template should describe a secure way to report a vulnerability

### ISSUE THREAD

**Issue by nealmcb** [maehr/github-template#18]
**Describe the bug**
The `github-template` suggestion for Security Policy (`SECURITY.md`) says:

_Reporting a Vulnerability
Please use the [GitHub Issue Tracker](https://github.com/USERNAME/REPO_NAME/issues) to report vulnerabilities._

**Expected behavior**
This is dangerous advice. GitHub does not support private issues reported by non-administrators, so this would instantly expose the vulnerability to the world, exacerbating the problem.

The advice given by [Scorecard](https://github.com/ossf/scorecard) says:
_The file should contain information on what constitutes a vulnerability and a way to report it securely (e.g. issue tracker with private issue support, encrypted email with a published public key)._

**Comment by maehr** [comment]
Thank you very much for your advice. I will implement it as soon as possible.

**Comment by maehr** [comment]
With #19 this issue was fixed.
